/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.4 */

#ifndef PB_CONTROL_MESSAGE_PB_H_INCLUDED
#define PB_CONTROL_MESSAGE_PB_H_INCLUDED
#include "pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Control {
    bool has_value;
    int32_t value;
} Control;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Control_init_default                     {false, 0}
#define Control_init_zero                        {false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Control_value_tag                        1

/* Struct field encoding specification for nanopb */
#define Control_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    value,             1)
#define Control_CALLBACK NULL
#define Control_DEFAULT NULL

extern const pb_msgdesc_t Control_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Control_fields &Control_msg

/* Maximum encoded size of messages (where known) */
#define Control_size                             11

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
